### PR TITLE
Feature/next

### PR DESCRIPTION
**Pull request by MangelMaxime**
**Changelog**

- If the platform is mobile or tablet, show a message explaining the REPL is only available on a desktop.

capture d ecran 2018-09-25 a 12 50 42

- If the browser is not Chrome or Safari then display a toast about recommended browsers

browser_advice

- Remove the navbar and move the `Compile` button in the sidebar
- Fix 1px offset in the submenu body when hovered
- Rework the settings widget
    - Improve the design
    - Allow choosing a font
       - Fira code that supports Ligature
       - Monaco default don't
   - Allow choosing a font size, 3 sizes (12px, 14px, 16px)
capture d ecran 2018-09-25 a 13 01 43
- Add statistics widget

capture d ecran 2018-09-25 a 13 02 24

-Fix sidebar behavior
    - Nested scroll works correctly

- Add toast on a compilation success/fail

- Improve editor display by setting the dimensions using pixels when possible. This allows us to use `flex`

- Add problems panel
    - Can be expanded/collapse
    - The user can click on a row to go to the error/warning in the editor
    - The user can hover a row to get the full error message in a tooltip

- Add console panel
    - Can be expanded/collapse
    - "Intelligent" auto scroll
        - If the scroll is at the bottom, auto scroll at the bottom when new logs are added
        - If the scroll isn't at the bottom, we don't move it when new logs are added

- Split the sidebar widgets into several files
- Fix visual glitch when hovering the right part of a button in the sidebar
- Add possibility to refresh the iframe without compilation.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
This is awesome, Maxime! What's missing? Merge it now! ;)

> I think you already know it but the problem with the red lines disappearing after compiling is fixed now.

Tabs are a bit the opposite move to @ncave suggestion of 4 panels, but I personally like them because I'm hiding the HTML panel all the time. This also keeps the symmetry with the Live/Code tabs :)

**Comment by MangelMaxime** [comment]
> What's missing? Merge it now! ;)

- I need to review my code, implements #28 
- And make a pass on the different idea we proposed in the different issue and see what can be done or no :).
- Check that everything is working on Chrome + Firefox, because the tooltip is pure CSS for "simplicity".

> Tabs are a bit the opposite move to @ncave suggestion of 4 panels

Indeed, we can think of a different layout of course but I think this one starts to make the REPL more usable than before :). For the current layout with the problem panel, when using vertical layout it's almost impossible to do correctly. Not enough space. I tried to think in term of editor and in general they works using tabs for this reason. Same goes for the others REPL or if they don't they offer the ability to the user to customize the layout or choose between different layouts.

I need to re-read @ncave proposition to remember the context. But I was kind of thinking to provide an ability to switch the right part of the REPL between tabs and vertical layouts.

**Comment by MangelMaxime** [comment]
**Add a statistic widget**

I remove the console output and made a clean widgets to show the different steps time on compilation:

capture d ecran 2018-09-21 a 15 48 45

*Designed has been approved by @selketjah* 

**Use a toast to notify the user when the shareable URL is ready**



**Improvement sidebar**

1. Make sure the `Collapse sidebar` button is always at the bottom of the screen
2. The sidebar shows a scrollbar is needed and support nested scroll bar.
    - A nested scroll is for example when we open all the widgets and some of the sample menu

**Comment by alfonsogarciacaro** [comment]
To try to match a bit all the awesomeness that @MangelMaxime is bringing to the REPL, I just added another feature that should also become quite helpful: go to definition 😸 

gotodefinition

**Comment by forki** [comment]
Wow. Is somethings of this already public?

Alfonso Garcia-Caro <notifications@github.com> schrieb am Sa., 22. Sep.
2018, 03:57:

**Comment by MangelMaxime** [comment]
@forki The go-to definition has been published to http://fable.io/repl2/

All the others feature listed in this PR isn't published yet. I hope to publish it over the weekend.

**Comment by MangelMaxime** [comment]
This evening update includes:

- Better design for the settings widget
- New settings:
  - Font Family
     - Monaco default
     - Fira Code (supports ligatures)
  - Font Size
    - Tooltip font size is also adapted according to current setting

**Comment by MangelMaxime** [comment]
Ok, I think this is the last big feature that was missing on my list, **the console panel**.

We are capturing `console.log`, `console.warn`, `console.error` and send them back into the application in order to display them in the **console panel**. We still print them in the **dev console** so there is no functionality loss.

Some limitation:
- For now, we only send back message have **1** argument or type `string`. Later we could handle several arguments and format them by our self.
- On `console.warn` and `console.error` we don't show the origin line. I didn't explore if this is do-able or no. But for now, it's out of scope for me as I just wanted to include a nice feedback in the REPL and not the "ugly" dev tool :)
- We keep only the last 200 logs in memory to avoid performance issue. Could be configurable or improved by using an intelligent view. Not sure this is really needed

Features:
- Visual feedback to show if this is a log, error, or warning.
- Add a "separator" that display `Iframe loaded`, so the user knows if this from a new instance or no.
- If the scroll is at the bottom, we auto scroll to the bottom when new logs are added
- If the scroll isn't at the bottom, we don't move the scroll on new logs. This is useful if the user is looking at a specific log and his application send them periodically.
- The console panel can be collapsed.



If everything is fine, I should be able tomorrow to resolve the conflict with the master branch. Prepare a message listing all the new features and perhaps gif so we can more easily communicate/tracks the new features. And finally, publish the new version if you (@ncave @forki @alfonsogarciacaro ) have no objection to any of the new features that I mentioned in the past days.

**Comment by alfonsogarciacaro** [comment]
PURE AWESOMENESS!!!

**Comment by forki** [comment]
😍 😍 😍 😍 😍

Btw: is this using some elmish?

**Comment by MangelMaxime** [comment]
@forki Yes the REPL, is an Elmish application.

Everything is using stateless components except 2 things:
- The monaco editor wrapper
- The console panel, because I need easy access to the references in order to control the auto scroll feature

**Comment by forki** [comment]
Awesome. This will be a great showcase for larger elmish app.

Maxime Mangel <notifications@github.com> schrieb am Di., 25. Sep. 2018,
07:49:

**Comment by forki** [comment]
Yes Page navigation is verbose in elmish.

Maxime Mangel <notifications@github.com> schrieb am Di., 25. Sep. 2018,
08:20:

**Comment by MangelMaxime** [comment]
I was more thinking about things like that:

I have a Domain entity used in:
1. DomainIndex page
2. DomainCreate page
3. DomainUpdate page

And I can't really mutualize the types because they don't need the same information depending on the page/context. I agree this is not something specific to Elmish because even when I was doing classic JavaScript I had this problem. But because use type everything this is much more visible :)

And it's also possible that there is nothing wrong too ^^.

**Comment by MangelMaxime** [comment]
I updated the first message so it served as a changelog

**Comment by MangelMaxime** [comment]
Everything has been published

**Pull request merged**
