### PR TITLE
Use a custom theme to match vs-dark style

### LINKED ISSUE #3: Bar colors
Obviously it's subjective, but I find that the white title bars and menu bar don't fit with the dark scheme and subtract from the experience.
Is it possible to have them changed to grey or textured grey? Like the toolbar color in any of VS Code dark themes, but it doesn't have to be exactly like that, just not white.

### LINKED ISSUE #6: (feature request) Reset button on top of the menu
Add reset button or reset item on the top of the menu to clean up the env (or reset to the initial script).

### PR DESCRIPTION
**Pull request by MangelMaxime**
Fix #3 , Fix #6 

### Some static view

**Expanded sidebar**
capture d ecran 2018-08-03 a 01 28 35

**Confirm reset**
capture d ecran 2018-08-03 a 01 28 48

**VSCode for comparison**
capture d ecran 2018-08-03 a 01 29 31

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Since a long time I wanted to test if we could customize Bulma to make it look like something totally different. I guess, we can say yes this is possible :)

I didn't add a lot of variables just the one I needed: https://github.com/fable-compiler/repl2/pull/7/files#diff-aff9c03493f0bad97b377ea1a1812dcf

**Comment by ncave** [comment]
@MangelMaxime This is awesome!

**Comment by alfonsogarciacaro** [comment]
OMG, I hope you had some time to sleep :wink:

**Comment by MangelMaxime** [comment]
Ahah no worries :)

**Pull request merged**
