### PR TITLE
Use react monaco

### PR DESCRIPTION
**Pull request by MangelMaxime**
Included in this PR:

- use `react-monaco-editor` instead of `monaco-editor`
- rework the sidebar components

**Sidebar demo**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Also, the `Samples` section is now scrollable when taking too much place in "Expanded mode".

**Comment by alfonsogarciacaro** [comment]
This is great @MangelMaxime! Thanks a lot! :clap: 😍 :clap:

**Comment by MangelMaxime** [comment]
Ah yes, I think webpack don't like the work and the HMR looks broken. The state seems to flicker a bit and in general, I can see the change but need to reload the page to make then persistant.

I don't think it's coming from the `react-monaco-editor` because I didn't see this problem in HTML to Elmsih or ts2fable online.

Just wanted to point that :)

**Comment by alfonsogarciacaro** [comment]
Yes, webpack logging says the worker cannot be cached so it probably interferes with HMR. Though it still seems to work for view-related changes.

**Comment by MangelMaxime** [comment]
The view changes are applied but flickering. 

In general, I see 

1. Old view
2. Update the code
3. HMR do it's stuff
4. New view
5. Old view
6. New view
7. Old view
etc.

But it's not like we are going to update the REPL UI every day :)

**Pull request merged**
