### PR TITLE
New libs & example

### PR DESCRIPTION
**Pull request by MangelMaxime**
Changes provided in this PR:

- Remove the `Counter` example because it provide no additional value compared to `Simple input`
- Add a new example `Random user (Thoth)`
    - Demonstrate how to use:
        - Thoth.Json
        - Fable.PowerPack.Promise
        - Fable.PowerPack.Fetch
- Rework the `src/Lib` folder
    - Move `src/Lib/Fable.Repl.Lib.fsproj` to `src/Lib/Fable.Repl.Lib/Fable.Repl.Lib.fsproj`
        - Contains the source code of the library
        - **No** bindings defintion
    - Create `src/Lib/Fable.Repl.Bindings/Fable.Repl.Bindings.fsproj` 
        - Contains the additional bindings definition needed by the libraries
        - Ex: `Fetch_types` module for `Fable.PowerPack.Fetch`
    - Create `src/Lib/Fable.Repl.Tests/Fable.Repl.Testsfsproj` 
        - Contains source files containing tests for the different libraries. This helps ensure we are not delivering a broken library.
        - For now, you need to copy/paste the source file manually but in the future we should be able to run it against node.

@alfonsogarciacaro While working on porting the different libraries I discovered new bugs/limitations of the JS version of Fable. I have listed them in [src/README.md](https://github.com/fable-compiler/repl2/compare/feature/new_libs?expand=1#diff-6b3c807a7e4b604ca0ed045197136205)

Can you please check if:
- I did something wrong
- They are real bugs
- They are just new limitations discovered

@forki @vbfox @Nhowka 
Can you please review the code I made for [the new example](https://github.com/fable-compiler/repl2/compare/feature/new_libs?expand=1#diff-c182504277799634d147673f462cda97). The goal, is to show how to use the different libraries by keeping it simple and clean (code and UI related).

Here is a GIF so you can see the example without having to compile the REPL.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Sorry about your PR for Recharts, we will need to update it to the new folder achitecture. But as the Gist support is included in it I think we should close it and copy/paste the Recharts bindings.

**Comment by Nhowka** [comment]
I love that example! It's simple and clear yet showing great power. It's sad that the computation expressions aren't working as the `promise` CE would make it even simpler.

**Comment by MangelMaxime** [comment]
Indeed, but perhaps this is just a bug or temporary limitation :)

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Great, thank you! Hmm, it's strange you cannot use object expressions or CEs, [they should be working](http://fable.io/repl2/#?code=C4TwDgpgBAkgYgewVAvAKCpqBDARgZ2ACdsBjYKRBALikKIEsA7AczTQBsIKAzJVKBiwBvKEwgB3WFSgSGwABZCsWALYRVuCESgB9XQDoZKKACI+CU1AC+7C0f4AfAHxQwjJsB5MzAUnym7FwUuNhEAIL4IEykUAAUAJQC2FExUKJE3ACuRD6moURWtmgp0bHCylAAJggAhFCRZQYAylwQYFAATAAMvZXB9fQCBY0xiZXuzF55-lb0aNZQLg2ppC3AYcAwqupVDNjAEEA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLswooOgBzLlYJPl5tcTo0MK8fXXEAdxiwEFYARgAGHPEQJGDwVjNcmGtPb18rJScXeEQVSFg4IA&css=Q). Do you have the "Optimize" option enabled? It seems they fail in that case.

Anyways I'll have a look, but feel free to merge if you want. Don't worry about my PR, I'll fix it. I need the Gist feature to quickly test things without publishing an example, so if you don't mind I'll merge it later but won't make the feature public so people don't know how to use it ;)

**Comment by MangelMaxime** [comment]
I need to check again for the CE but I didn't add this errors. 
The errors I had was more `failed to load member xxx in module yyy`.

I don't like the idea of publishing something that can partially works but as you want. Be sure, that if we publish it some people with discover it and use it.

What do you mean by quickly tests things ?

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Do you know why [Encode.nil](https://github.com/fable-compiler/repl2/compare/feature/new_libs?expand=1#diff-6b3c807a7e4b604ca0ed045197136205R100) generates wrong code ?

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime I'm looking into this. I think if we start adding more files to the Repl Lib, it's going to be a maintenance nightmare if we have to keep the modified versions in sync with the sources, and it may be confusing for the users too. I'm working now on a solution so we don't need to make modifications to the files to include them in the Repl Lib.

About `Encode.nil` I guess we need [add a check here](https://github.com/fable-compiler/Fable/blob/2ece26e5ea586af4ca3423d72f4d370077a9c27e/src/dotnet/Fable.Compiler/Transforms/Replacements.fs#L976-L979) to see if the imported member is a value or a function.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Indeed having to maintain 2 versions of a lib is a problem. For example, Thoth.Json is already out of sync :D

If we are able to do something like:

- Use `paket-files` to include a source file reference
- Have a `Fake` target to copy the source files and add `namespace Fable.Repl.Lib`
- If Fable detect `namespace Fable.Repl.Lib` ignore some special structure like `public inline` if it's possible

My idea is very naive and I think it's probably not possible for everything. But at least, we have a script to do small modification of the source code it should be a huge step forward.

Or perhaps, now that we can support multi file support depending on the performance we could have an interface (in the menu) to add/remove libraries. And compile it directly in the browser and cache it.

It's similar to what the ELM editor is doing or babel repl do for the plugin I think.

**Pull request closed without merging**
