### PR TITLE
Updated monaco bindings

### PR DESCRIPTION
**Pull request by ncave**
Seems to work.

Note: There is some monaco webworker error in the browser console, perhaps some missing monaco configuration, but it does not seem to affect functionality. Let me know if you've seen it before or have any idea how to get rid of it.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I disabled some feature or monaco in the webpack config.  

But in theory if there are disabled they should not create an error. Check for the monaco webpack plugin initialisation if you want to take a look

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by ncave** [comment]
Looks like what is happening is that the monaco webworker environment is not correctly set up.
[Here](https://github.com/Microsoft/monaco-editor/tree/master/docs) is the documentation on how to properly integrate the editor.

**Comment by MangelMaxime** [comment]
Hum the webpack plugin should do all the job for us. Otherwise, I would call it almost useless :)

At least, I think in previous version we didn't have the errors. But perhaps, I remember incorrectly

**Comment by ncave** [comment]
Here is where the error happens:
```
self["MonacoEnvironment"] = (function (paths) {
      function stripTrailingSlash(str) {
        return str.replace(/\/$/, '');
      }
      return {
        getWorkerUrl: function (moduleId, label) {
          const pathPrefix = (typeof window.__webpack_public_path__ === 'string' ? window.__webpack_public_path__ : "");
          return (pathPrefix ? stripTrailingSlash(pathPrefix) + '/' : '') + paths[label];
        }
      };
    })({
  "editorWorkerService": "editor.worker.js",
  "html": "html.worker.js",
  "css": "css.worker.js",
  "less": "css.worker.js",
  "scss": "css.worker.js"
});
```
There is a missing webworker label (path) at the bottom, called `javascript`, so it's failing.

**Comment by MangelMaxime** [comment]
Perhaps [this line](https://github.com/fable-compiler/repl2/blob/master/webpack.config.js#L51) is false ? Or we could remove it as user will not write JavaScript in theory...

**Comment by ncave** [comment]
@MangelMaxime That was the first thing I tried, unfortunately does not help, same thing. Not sure where is the script above coming from, is that from the plugin?

**Comment by alfonsogarciacaro** [comment]
Sorry, I thought I had merged this but apparently I forgot to click the button on my phone. Should I wait? BTW, off the top of my head I think looking at the sources of the REPL I saw a typescript worker but not a Javascript one. I just assumed in Monaco/VS Code the typescript compiler is also used to check JS editors.

**Comment by ncave** [comment]
@alfonsogarciacaro It's up to you, it works but there is a console error, as stated above, about the javascript web worker path.

**Comment by alfonsogarciacaro** [comment]
I don't have Wi-Fi atm and I'm very close to reaching my data limit so I'll wait before merging and making the build but if Maxime wants and has the opportunity, maybe he can try using the typescript worker and making a release.

**Comment by MangelMaxime** [comment]
Will try too take a look today or tomorrow

**Comment by ncave** [comment]
This PR is not in any way urgent or anything, I don't think it adds any new functionality that we are missing (just binding update) so there is no rush at all to merge it. Please take your time and most certainly don't interrupt your vacation for something trivial like that :) Have a nice summer!

**Comment by alfonsogarciacaro** [comment]
Found this: https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/27

The solution seems to work but there's now an error with monaco 0.14.3, I had to pin the version to 0.14.2.

**Pull request merged**
